name: Deploy to Production on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Zip Lambda function
        run: |
          zip function.zip lambda_function.py
      
      - name: Upload Lambda code to S3 (Production)
        run: |
          aws s3 cp function.zip s3://${{ secrets.S3_BUCKET_PROD }}/${{ secrets.S3_PATH_PROD }}
      
      - name: Deploy CloudFormation stack (Production)
        run: |
          aws cloudformation deploy \
            --stack-name ${{ secrets.CF_STACK_NAME_PROD }} \
            --template-file infrastructure/cloudformation/lambda-ec2-shutdown.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaFunctionName=${{ secrets.LAMBDA_NAME_PROD }} \
              LambdaCodeBucket=${{ secrets.S3_BUCKET_PROD }} \
              LambdaCodeKey=${{ secrets.S3_PATH_PROD }}
